version: "3.7"

services:
  db:
    image: 'mysql:5.7'
    ports:
    - 3307:3306
    environment:
      MYSQL_DATABASE: express_crud
      MYSQL_ROOT_PASSWORD: rnjsgusqls0304
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
